package org.dals.project.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import org.dals.project.model.*
import org.dals.project.repository.AuthRepository
import org.dals.project.repository.LoanRepository
import org.dals.project.repository.NotificationRepository
import org.dals.project.utils.SnackbarManager

data class LoanUiState(
    val isLoading: Boolean = false,
    val currentUser: User? = null,
    val loanApplications: List<LoanApplication> = emptyList(),
    val activeLoans: List<Loan> = emptyList(),
    val selectedLoan: Loan? = null,
    val errorMessage: String? = null,
    val successMessage: String? = null
)

class LoanViewModel(
    private val authRepository: AuthRepository,
    private val notificationRepository: NotificationRepository? = null
) : ViewModel() {

    private val repository = LoanRepository(authRepository)
    private val _uiState = MutableStateFlow(LoanUiState())
    val uiState: StateFlow<LoanUiState> = _uiState.asStateFlow()

    private var inactivityManager: org.dals.project.utils.InactivityManager? = null

    init {
        loadInitialData()
    }

    fun setInactivityManager(manager: org.dals.project.utils.InactivityManager) {
        this.inactivityManager = manager
    }

    private fun resetInactivityTimer() {
        inactivityManager?.resetTimer()
    }

    private fun loadInitialData() {
        viewModelScope.launch {
            _uiState.value = _uiState.value.copy(isLoading = true)

            try {
                // Collect data from repositories
                launch {
                    authRepository.currentUser.collect { user ->
                        _uiState.value = _uiState.value.copy(currentUser = user)
                    }
                }

                launch {
                    repository.loanApplications.collect { applications ->
                        _uiState.value = _uiState.value.copy(loanApplications = applications)
                    }
                }

                launch {
                    repository.activeLoans.collect { loans ->
                        _uiState.value = _uiState.value.copy(activeLoans = loans)
                    }
                }

            } finally {
                _uiState.value = _uiState.value.copy(isLoading = false)
            }
        }
    }

    fun submitLoanApplication(
        amount: Double,
        purpose: LoanPurpose,
        termInMonths: Int,
        description: String,
        collateralType: CollateralType,
        collateralValue: Double,
        employmentInfo: EmploymentInfo,
        monthlyIncome: Double,
        existingDebts: Double
    ) {
        viewModelScope.launch {
            _uiState.value = _uiState.value.copy(isLoading = true, errorMessage = null)

            val currentUser = _uiState.value.currentUser
            if (currentUser == null) {
                _uiState.value = _uiState.value.copy(
                    isLoading = false,
                    errorMessage = "User not found"
                )
                return@launch
            }

            val application = LoanApplication(
                id = "", // Will be generated by repository
                borrowerId = currentUser.id,
                amount = amount,
                purpose = purpose,
                termInMonths = termInMonths,
                interestRate = calculateInterestRate(amount, termInMonths, currentUser.creditScore),
                collateralType = collateralType,
                collateralValue = collateralValue,
                status = LoanStatus.DRAFT,
                applicationDate = "2024-01-15T10:30:00", // Will be set by repository
                description = description,
                employmentInfo = employmentInfo,
                monthlyIncome = monthlyIncome,
                existingDebts = existingDebts
            )

            repository.submitLoanApplication(application)
                .onSuccess { applicationId ->
                    val message = "Loan application submitted successfully! ID: $applicationId"
                    _uiState.value = _uiState.value.copy(
                        isLoading = false,
                        successMessage = message
                    )
                    SnackbarManager.showSuccess(message)
                    // Refresh notifications after successful loan submission
                    viewModelScope.launch {
                        notificationRepository?.refreshNotifications()
                    }
                }
                .onFailure { error ->
                    val message = "Failed to submit application: ${error.message}"
                    _uiState.value = _uiState.value.copy(
                        isLoading = false,
                        errorMessage = message
                    )
                    SnackbarManager.showError(message)
                }
        }
    }

    fun makePayment(loanId: String, amount: Double) {
        viewModelScope.launch {
            _uiState.value = _uiState.value.copy(isLoading = true, errorMessage = null)

            repository.makePayment(loanId, amount)
                .onSuccess { message ->
                    // Data will be automatically refreshed through the repository's flow
                    _uiState.value = _uiState.value.copy(
                        isLoading = false,
                        successMessage = message
                    )
                    SnackbarManager.showSuccess(message)
                    // Refresh notifications after successful loan payment
                    viewModelScope.launch {
                        notificationRepository?.refreshNotifications()
                    }
                }
                .onFailure { error ->
                    val message = "Payment failed: ${error.message}"
                    _uiState.value = _uiState.value.copy(
                        isLoading = false,
                        errorMessage = message
                    )
                    SnackbarManager.showError(message)
                }
        }
    }

    fun selectLoan(loan: Loan) {
        _uiState.value = _uiState.value.copy(selectedLoan = loan)
    }

    fun clearMessages() {
        _uiState.value = _uiState.value.copy(
            errorMessage = null,
            successMessage = null
        )
    }

    private fun calculateInterestRate(amount: Double, termInMonths: Int, creditScore: Int): Double {
        // Simple interest rate calculation based on credit score and loan parameters
        val baseRate = when {
            creditScore >= 750 -> 5.0
            creditScore >= 700 -> 7.0
            creditScore >= 650 -> 9.0
            creditScore >= 600 -> 12.0
            else -> 15.0
        }

        // Add risk premium for larger amounts or longer terms
        val amountPremium = if (amount > 20000) 1.0 else 0.0
        val termPremium = if (termInMonths > 24) 0.5 else 0.0

        return baseRate + amountPremium + termPremium
    }

    fun getLoanById(loanId: String): Loan? {
        return _uiState.value.activeLoans.find { it.id == loanId }
    }

    fun getApplicationById(applicationId: String): LoanApplication? {
        return _uiState.value.loanApplications.find { it.id == applicationId }
    }
}